title: "AI 情报简报"
description: "每日聚合 AI 领域最新资讯、论文、项目与观点"
url: "https://pierrelzw.github.io"
baseurl: "/AI-News"
timezone: Asia/Tokyo
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 20
  permalink: '/page/:num/'
  title: ':title - 第 :num 页'
  sort_field: 'date'
  sort_reverse: true